/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sistema;

import java.awt.Color;
import teste.Pintar_Cabecalho;

/**
 *
 * @author Refrigeração Josemaq
 */
public class TABELA_EXEMPLO extends javax.swing.JFrame {

    /**
     * Creates new form TABELA_000
     */
    public TABELA_EXEMPLO() {
        initComponents();
        Tabela_Dados.getColumnModel().getColumn(0).setHeaderRenderer(new Pintar_Cabecalho(new java.awt.Font("Open Sans Semibold", 1, 12),true,Color.WHITE,Color.GRAY));
        Tabela_Dados.getColumnModel().getColumn(1).setHeaderRenderer(new Pintar_Cabecalho(new java.awt.Font("Open Sans Semibold", 1, 12),true,Color.WHITE,Color.GRAY));
        Tabela_Dados.getColumnModel().getColumn(2).setHeaderRenderer(new Pintar_Cabecalho(new java.awt.Font("Open Sans Semibold", 1, 12),true,Color.WHITE,Color.GRAY));
        Tabela_Dados.getColumnModel().getColumn(3).setHeaderRenderer(new Pintar_Cabecalho(new java.awt.Font("Open Sans Semibold", 1, 12),true,Color.WHITE,Color.GRAY));
        Tabela_Dados.getColumnModel().getColumn(4).setHeaderRenderer(new Pintar_Cabecalho(new java.awt.Font("Open Sans Semibold", 1, 12),true,Color.WHITE,Color.GRAY));
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        Tabela_DadosPessoais1 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        Tabela_Dados = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane4.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane4.setForeground(new java.awt.Color(102, 102, 102));
        jScrollPane4.setToolTipText("");
        jScrollPane4.setFocusable(false);
        jScrollPane4.setFont(new java.awt.Font("Open Sans Semibold", 0, 16)); // NOI18N
        jScrollPane4.setMinimumSize(new java.awt.Dimension(10, 10));

        Tabela_DadosPessoais1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Tabela_DadosPessoais1.setFont(new java.awt.Font("Open Sans Semibold", 1, 12)); // NOI18N
        Tabela_DadosPessoais1.setForeground(new java.awt.Color(51, 51, 51));
        Tabela_DadosPessoais1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NOME", "CPF", "RG", "ORGAO", "SEXO", "NASCIMENTO", "ESTADO CIVIL", "SALARIO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabela_DadosPessoais1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Tabela_DadosPessoais1.setDragEnabled(true);
        Tabela_DadosPessoais1.setEditingColumn(0);
        Tabela_DadosPessoais1.setEditingRow(0);
        Tabela_DadosPessoais1.setGridColor(new java.awt.Color(255, 255, 255));
        Tabela_DadosPessoais1.setIntercellSpacing(new java.awt.Dimension(5, 0));
        Tabela_DadosPessoais1.setMinimumSize(new java.awt.Dimension(75, 315));
        Tabela_DadosPessoais1.setRequestFocusEnabled(false);
        Tabela_DadosPessoais1.setRowHeight(35);
        Tabela_DadosPessoais1.setSelectionBackground(new java.awt.Color(255, 255, 255));
        Tabela_DadosPessoais1.setSelectionForeground(new java.awt.Color(10, 174, 239));
        Tabela_DadosPessoais1.setShowHorizontalLines(false);
        Tabela_DadosPessoais1.setShowVerticalLines(false);
        Tabela_DadosPessoais1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Tabela_DadosPessoais1FocusGained(evt);
            }
        });
        Tabela_DadosPessoais1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Tabela_DadosPessoais1KeyTyped(evt);
            }
        });
        jScrollPane4.setViewportView(Tabela_DadosPessoais1);

        jScrollPane5.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane5.setForeground(new java.awt.Color(102, 102, 102));
        jScrollPane5.setToolTipText("");
        jScrollPane5.setFocusable(false);
        jScrollPane5.setFont(new java.awt.Font("Open Sans Semibold", 0, 16)); // NOI18N
        jScrollPane5.setMinimumSize(new java.awt.Dimension(10, 10));

        Tabela_Dados.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Tabela_Dados.setFont(new java.awt.Font("Open Sans Semibold", 1, 12)); // NOI18N
        Tabela_Dados.setForeground(new java.awt.Color(51, 51, 51));
        Tabela_Dados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID PRODUTO", "NOME", "RG", "ORGAO", "SEXO", "NASCIMENTO", "ESTADO CIVIL", "SALARIO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabela_Dados.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Tabela_Dados.setDragEnabled(true);
        Tabela_Dados.setEditingColumn(0);
        Tabela_Dados.setEditingRow(0);
        Tabela_Dados.setGridColor(new java.awt.Color(255, 255, 255));
        Tabela_Dados.setIntercellSpacing(new java.awt.Dimension(5, 0));
        Tabela_Dados.setMinimumSize(new java.awt.Dimension(75, 315));
        Tabela_Dados.setRequestFocusEnabled(false);
        Tabela_Dados.setRowHeight(35);
        Tabela_Dados.setSelectionBackground(new java.awt.Color(255, 255, 255));
        Tabela_Dados.setSelectionForeground(new java.awt.Color(10, 174, 239));
        Tabela_Dados.setShowHorizontalLines(false);
        Tabela_Dados.setShowVerticalLines(false);
        Tabela_Dados.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Tabela_DadosFocusGained(evt);
            }
        });
        Tabela_Dados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Tabela_DadosKeyTyped(evt);
            }
        });
        jScrollPane5.setViewportView(Tabela_Dados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(184, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(121, 121, 121))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Tabela_DadosPessoais1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Tabela_DadosPessoais1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_Tabela_DadosPessoais1FocusGained

    private void Tabela_DadosPessoais1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Tabela_DadosPessoais1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_Tabela_DadosPessoais1KeyTyped

    private void Tabela_DadosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Tabela_DadosFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_Tabela_DadosFocusGained

    private void Tabela_DadosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Tabela_DadosKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_Tabela_DadosKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TABELA_EXEMPLO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TABELA_EXEMPLO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TABELA_EXEMPLO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TABELA_EXEMPLO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TABELA_EXEMPLO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabela_Dados;
    private javax.swing.JTable Tabela_DadosPessoais1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    // End of variables declaration//GEN-END:variables
}
