/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sistema;

import java.awt.Color;
import teste.Pintar_Cabecalho;

/**
 *
 * @author Refrigeração Josemaq
 */
public class Tela_35_User2_Pagamentos extends javax.swing.JFrame {

    /**
     * Creates new form Tela_32_User2_Pagamentos
     */
    public Tela_35_User2_Pagamentos() {
        initComponents();
        Tabela_Pagamento.getColumnModel().getColumn(0).setHeaderRenderer(new Pintar_Cabecalho(new java.awt.Font("Open Sans Semibold", 1, 12),true,Color.WHITE,Color.GRAY));
        Tabela_Pagamento.getColumnModel().getColumn(1).setHeaderRenderer(new Pintar_Cabecalho(new java.awt.Font("Open Sans Semibold", 1, 12),true,Color.WHITE,Color.GRAY));
        Tabela_Pagamento.getColumnModel().getColumn(2).setHeaderRenderer(new Pintar_Cabecalho(new java.awt.Font("Open Sans Semibold", 1, 12),true,Color.WHITE,Color.GRAY));
        Tabela_Pagamento.getColumnModel().getColumn(3).setHeaderRenderer(new Pintar_Cabecalho(new java.awt.Font("Open Sans Semibold", 1, 12),true,Color.WHITE,Color.GRAY));
        Tabela_Pagamento.getColumnModel().getColumn(4).setHeaderRenderer(new Pintar_Cabecalho(new java.awt.Font("Open Sans Semibold", 1, 12),true,Color.WHITE,Color.GRAY));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Button_Tela35_TelaAnterior = new javax.swing.JLabel();
        Button_Tela35_RetornarMenu = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        Tabela_Pagamento = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Button_Tela35_TelaAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ButtonsUser2/tela-anterior.png"))); // NOI18N
        Button_Tela35_TelaAnterior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_Tela35_TelaAnteriorMouseClicked(evt);
            }
        });
        getContentPane().add(Button_Tela35_TelaAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, -1, 40));

        Button_Tela35_RetornarMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ButtonsUsoGeral/Global.png"))); // NOI18N
        Button_Tela35_RetornarMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_Tela35_RetornarMenuMouseClicked(evt);
            }
        });
        getContentPane().add(Button_Tela35_RetornarMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, 40));

        jScrollPane5.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane5.setForeground(new java.awt.Color(102, 102, 102));
        jScrollPane5.setToolTipText("");
        jScrollPane5.setFocusable(false);
        jScrollPane5.setFont(new java.awt.Font("Open Sans Semibold", 0, 16)); // NOI18N
        jScrollPane5.setMinimumSize(new java.awt.Dimension(10, 10));

        Tabela_Pagamento.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Tabela_Pagamento.setFont(new java.awt.Font("Open Sans Semibold", 1, 12)); // NOI18N
        Tabela_Pagamento.setForeground(new java.awt.Color(51, 51, 51));
        Tabela_Pagamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID_PAGAMENTO", "PARCELAS", "DATA_PAGAM", "FORMA_PAGAMENTO", "VALOR_COMPRA", "ID_COMPRA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabela_Pagamento.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Tabela_Pagamento.setDragEnabled(true);
        Tabela_Pagamento.setEditingColumn(0);
        Tabela_Pagamento.setEditingRow(0);
        Tabela_Pagamento.setGridColor(new java.awt.Color(255, 255, 255));
        Tabela_Pagamento.setIntercellSpacing(new java.awt.Dimension(5, 0));
        Tabela_Pagamento.setMinimumSize(new java.awt.Dimension(75, 315));
        Tabela_Pagamento.setRequestFocusEnabled(false);
        Tabela_Pagamento.setRowHeight(35);
        Tabela_Pagamento.setSelectionBackground(new java.awt.Color(255, 255, 255));
        Tabela_Pagamento.setSelectionForeground(new java.awt.Color(10, 174, 239));
        Tabela_Pagamento.setShowHorizontalLines(false);
        Tabela_Pagamento.setShowVerticalLines(false);
        Tabela_Pagamento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Tabela_PagamentoFocusGained(evt);
            }
        });
        Tabela_Pagamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Tabela_PagamentoKeyTyped(evt);
            }
        });
        jScrollPane5.setViewportView(Tabela_Pagamento);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 530, 250));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/BackgroundsUser2/22.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -30, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Button_Tela35_RetornarMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_Tela35_RetornarMenuMouseClicked
        // TODO add your handling code here:
        new Tela_14_User2_Menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_Button_Tela35_RetornarMenuMouseClicked

    private void Button_Tela35_TelaAnteriorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_Tela35_TelaAnteriorMouseClicked
        // TODO add your handling code here:
        new Tela_34_User2_MenuCliente().setVisible(true);
        dispose();
    }//GEN-LAST:event_Button_Tela35_TelaAnteriorMouseClicked

    private void Tabela_PagamentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Tabela_PagamentoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_Tabela_PagamentoFocusGained

    private void Tabela_PagamentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Tabela_PagamentoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_Tabela_PagamentoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windowns".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_35_User2_Pagamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_35_User2_Pagamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_35_User2_Pagamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_35_User2_Pagamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_35_User2_Pagamentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Button_Tela35_RetornarMenu;
    private javax.swing.JLabel Button_Tela35_TelaAnterior;
    private javax.swing.JTable Tabela_Pagamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane5;
    // End of variables declaration//GEN-END:variables
}
