/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sistema;

import Classes.DadosCliente;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import teste.Pintar_Cabecalho;

/**
 *
 * @author Refrigeração Josemaq
 */
public class Tela_26_User2_VerTabelaDados extends javax.swing.JFrame {

    /**
     * Creates new form Tela_26_User2_VerTabelaDados
     */
    public Tela_26_User2_VerTabelaDados() {
        initComponents();
        mostrar_dadosCliente();
        Tabela_Dados.getColumnModel().getColumn(0).setHeaderRenderer(new Pintar_Cabecalho(new java.awt.Font("Open Sans Semibold", 1, 12),true,Color.WHITE,Color.GRAY));
        Tabela_Dados.getColumnModel().getColumn(1).setHeaderRenderer(new Pintar_Cabecalho(new java.awt.Font("Open Sans Semibold", 1, 12),true,Color.WHITE,Color.GRAY));
        Tabela_Dados.getColumnModel().getColumn(2).setHeaderRenderer(new Pintar_Cabecalho(new java.awt.Font("Open Sans Semibold", 1, 12),true,Color.WHITE,Color.GRAY));
        Tabela_Dados.getColumnModel().getColumn(3).setHeaderRenderer(new Pintar_Cabecalho(new java.awt.Font("Open Sans Semibold", 1, 12),true,Color.WHITE,Color.GRAY));
        Tabela_Dados.getColumnModel().getColumn(4).setHeaderRenderer(new Pintar_Cabecalho(new java.awt.Font("Open Sans Semibold", 1, 12),true,Color.WHITE,Color.GRAY));
        Tabela_Dados.getColumnModel().getColumn(5).setHeaderRenderer(new Pintar_Cabecalho(new java.awt.Font("Open Sans Semibold", 1, 12),true,Color.WHITE,Color.GRAY));
        Tabela_Dados.getColumnModel().getColumn(6).setHeaderRenderer(new Pintar_Cabecalho(new java.awt.Font("Open Sans Semibold", 1, 12),true,Color.WHITE,Color.GRAY));
        Tabela_Dados.getColumnModel().getColumn(7).setHeaderRenderer(new Pintar_Cabecalho(new java.awt.Font("Open Sans Semibold", 1, 12),true,Color.WHITE,Color.GRAY));
        Tabela_Dados.getColumnModel().getColumn(8).setHeaderRenderer(new Pintar_Cabecalho(new java.awt.Font("Open Sans Semibold", 1, 12),true,Color.WHITE,Color.GRAY));
       
    }
    public ArrayList<DadosCliente> dadosClienteLista(){
        ArrayList<DadosCliente> dadosClienteLista = new ArrayList<>();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection
            ("jdbc:mysql://localhost:3306/gerenciamento","root","");
            String sql ="select id_cliente,nome,cpf,rg,orgao,sexo,nascimento,estado_civil,salario from cliente";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            DadosCliente dadosCliente;
            while(rs.next()){
                dadosCliente = new DadosCliente(rs.getInt("id_cliente"),rs.getString("nome"),rs.getString("cpf"),rs.getString("rg"),rs.getString("orgao"),rs.getString("sexo"),rs.getDate("nascimento"),rs.getString("estado_civil"),rs.getDouble("salario"));
                dadosClienteLista.add(dadosCliente);
            }
        }
        catch(ClassNotFoundException | SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
        return dadosClienteLista;
        
    }
    public void mostrar_dadosCliente(){
        ArrayList<DadosCliente> lista = dadosClienteLista();
        DefaultTableModel modelo =(DefaultTableModel) Tabela_Dados.getModel();
        Object [] coluna = new Object[9];
        for(int i = 0; i<lista.size();i++){
            coluna[0]=lista.get(i).getid_cliente();
            coluna[1]=lista.get(i).getnome();
            coluna[2]=lista.get(i).getcpf();
            coluna[3]=lista.get(i).getrg();
            coluna[4]=lista.get(i).getorgao();
            coluna[5]=lista.get(i).getsexo();
            coluna[6]=lista.get(i).getdata_nascimento();
            coluna[7]=lista.get(i).getestadoCivil();
            coluna[8]=lista.get(i).getsalario();
            modelo.addRow(coluna);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Button_Tela26_RetornarMenu = new javax.swing.JLabel();
        Button_Tela26_VerTabelaLocal = new javax.swing.JLabel();
        Button_Tela26_VoltarAtualizacao = new javax.swing.JLabel();
        Button_Tela26_VerTabelaContato = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        Tabela_Dados = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Button_Tela26_RetornarMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ButtonsUser2/Voltar-Ao-Menu.png"))); // NOI18N
        Button_Tela26_RetornarMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_Tela26_RetornarMenuMouseClicked(evt);
            }
        });
        getContentPane().add(Button_Tela26_RetornarMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, -1, -1));

        Button_Tela26_VerTabelaLocal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ButtonsUser2/Localização-do-Cliente.png"))); // NOI18N
        Button_Tela26_VerTabelaLocal.setToolTipText("");
        Button_Tela26_VerTabelaLocal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_Tela26_VerTabelaLocalMouseClicked(evt);
            }
        });
        getContentPane().add(Button_Tela26_VerTabelaLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 370, -1, -1));

        Button_Tela26_VoltarAtualizacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ButtonsUser2/Voltar-para-Atualização.png"))); // NOI18N
        Button_Tela26_VoltarAtualizacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_Tela26_VoltarAtualizacaoMouseClicked(evt);
            }
        });
        getContentPane().add(Button_Tela26_VoltarAtualizacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, -1, -1));

        Button_Tela26_VerTabelaContato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ButtonsUser2/Tabela-de-Contato.png"))); // NOI18N
        Button_Tela26_VerTabelaContato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_Tela26_VerTabelaContatoMouseClicked(evt);
            }
        });
        getContentPane().add(Button_Tela26_VerTabelaContato, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 370, -1, -1));

        jScrollPane4.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane4.setForeground(new java.awt.Color(102, 102, 102));
        jScrollPane4.setToolTipText("");
        jScrollPane4.setFocusable(false);
        jScrollPane4.setFont(new java.awt.Font("Open Sans Semibold", 0, 16)); // NOI18N
        jScrollPane4.setMinimumSize(new java.awt.Dimension(10, 10));

        Tabela_Dados.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Tabela_Dados.setFont(new java.awt.Font("Open Sans Semibold", 1, 12)); // NOI18N
        Tabela_Dados.setForeground(new java.awt.Color(51, 51, 51));
        Tabela_Dados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "CPF", "RG", "ORGAO", "SEXO", "NASCIMENTO", "ESTADO CIVIL", "SALARIO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabela_Dados.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Tabela_Dados.setDragEnabled(true);
        Tabela_Dados.setEditingColumn(0);
        Tabela_Dados.setEditingRow(0);
        Tabela_Dados.setGridColor(new java.awt.Color(255, 255, 255));
        Tabela_Dados.setIntercellSpacing(new java.awt.Dimension(5, 0));
        Tabela_Dados.setMinimumSize(new java.awt.Dimension(75, 315));
        Tabela_Dados.setRequestFocusEnabled(false);
        Tabela_Dados.setRowHeight(35);
        Tabela_Dados.setSelectionBackground(new java.awt.Color(255, 255, 255));
        Tabela_Dados.setSelectionForeground(new java.awt.Color(10, 174, 239));
        Tabela_Dados.setShowHorizontalLines(false);
        Tabela_Dados.setShowVerticalLines(false);
        Tabela_Dados.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Tabela_DadosFocusGained(evt);
            }
        });
        Tabela_Dados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Tabela_DadosKeyTyped(evt);
            }
        });
        jScrollPane4.setViewportView(Tabela_Dados);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 820, 240));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/BackgroundsUser2/13.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Button_Tela26_VerTabelaLocalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_Tela26_VerTabelaLocalMouseClicked
        // TODO add your handling code here:
        new Tela_27_User2_VerTabelaDadosLocalizacao().setVisible(true);
        dispose();
    }//GEN-LAST:event_Button_Tela26_VerTabelaLocalMouseClicked

    private void Button_Tela26_RetornarMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_Tela26_RetornarMenuMouseClicked
        // TODO add your handling code here:
        new Tela_14_User2_Menu(). setVisible(true);
        dispose();
    }//GEN-LAST:event_Button_Tela26_RetornarMenuMouseClicked

    private void Button_Tela26_VoltarAtualizacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_Tela26_VoltarAtualizacaoMouseClicked
        // TODO add your handling code here:
        new Tela_24_User2_AtualizarDadosCliente(). setVisible(true);
        dispose();
    }//GEN-LAST:event_Button_Tela26_VoltarAtualizacaoMouseClicked

    private void Button_Tela26_VerTabelaContatoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_Tela26_VerTabelaContatoMouseClicked
        // TODO add your handling code here:
        new Tela_28_User2_VerTabelaDadosContato(). setVisible(true);
        dispose();
    }//GEN-LAST:event_Button_Tela26_VerTabelaContatoMouseClicked

    private void Tabela_DadosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Tabela_DadosFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_Tabela_DadosFocusGained

    private void Tabela_DadosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Tabela_DadosKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_Tabela_DadosKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windowns".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_26_User2_VerTabelaDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_26_User2_VerTabelaDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_26_User2_VerTabelaDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_26_User2_VerTabelaDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_26_User2_VerTabelaDados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Button_Tela26_RetornarMenu;
    private javax.swing.JLabel Button_Tela26_VerTabelaContato;
    private javax.swing.JLabel Button_Tela26_VerTabelaLocal;
    private javax.swing.JLabel Button_Tela26_VoltarAtualizacao;
    private javax.swing.JTable Tabela_Dados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
