/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sistema;

/**
 *
 * @author Refrigeração Josemaq
 */
public class Tela_25_User2_PosAtualizar extends javax.swing.JFrame {

    /**
     * Creates new form Tela_25_User2_PosAtualizar
     */
    public Tela_25_User2_PosAtualizar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Button_Tela25_RetornarMenu = new javax.swing.JLabel();
        Button_Tela25_VerTabela = new javax.swing.JLabel();
        Buton_Tela25_AtualizarOutro = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Button_Tela25_RetornarMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ButtonsUser2/retmenu.png"))); // NOI18N
        Button_Tela25_RetornarMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_Tela25_RetornarMenuMouseClicked(evt);
            }
        });
        getContentPane().add(Button_Tela25_RetornarMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, -1, -1));

        Button_Tela25_VerTabela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ButtonsUser2/vertabela.png"))); // NOI18N
        Button_Tela25_VerTabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_Tela25_VerTabelaMouseClicked(evt);
            }
        });
        getContentPane().add(Button_Tela25_VerTabela, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 280, -1, -1));

        Buton_Tela25_AtualizarOutro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ButtonsUser2/attoutro.png"))); // NOI18N
        Buton_Tela25_AtualizarOutro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Buton_Tela25_AtualizarOutroMouseClicked(evt);
            }
        });
        getContentPane().add(Buton_Tela25_AtualizarOutro, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/BackgroundsUser2/12.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Buton_Tela25_AtualizarOutroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Buton_Tela25_AtualizarOutroMouseClicked
        // TODO add your handling code here:
        new Tela_24_User2_AtualizarDadosCliente().setVisible(true);
        dispose();
    }//GEN-LAST:event_Buton_Tela25_AtualizarOutroMouseClicked

    private void Button_Tela25_RetornarMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_Tela25_RetornarMenuMouseClicked
        // TODO add your handling code here:
        new Tela_14_User2_Menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_Button_Tela25_RetornarMenuMouseClicked

    private void Button_Tela25_VerTabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_Tela25_VerTabelaMouseClicked
        // TODO add your handling code here:
        new Tela_26_User2_VerTabelaDados().setVisible(true);
        dispose();
    }//GEN-LAST:event_Button_Tela25_VerTabelaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windowns".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_25_User2_PosAtualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_25_User2_PosAtualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_25_User2_PosAtualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_25_User2_PosAtualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_25_User2_PosAtualizar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Buton_Tela25_AtualizarOutro;
    private javax.swing.JLabel Button_Tela25_RetornarMenu;
    private javax.swing.JLabel Button_Tela25_VerTabela;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
