/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sistema;

import Conexao_e_Tabela.connectionFactory;
import Model_Bean.Ocorrencia;
import Model_DAO.OcorrenciaDAO;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import teste.Pintar_Cabecalho;


/**
 *
 * @author Refrigeração Josemaq
 */
public class Tela5_RelatoriosUser1 extends javax.swing.JFrame {

    /**
     * Creates new form Tela5_RelatóriosUser1
     */
    public Tela5_RelatoriosUser1() {
        initComponents();
        Tabela_Ocorrencias.getColumnModel().getColumn(0).setHeaderRenderer(new Pintar_Cabecalho(new java.awt.Font("Open Sans Semibold", 1, 12),true,Color.WHITE,Color.GRAY));
        Tabela_Ocorrencias.getColumnModel().getColumn(1).setHeaderRenderer(new Pintar_Cabecalho(new java.awt.Font("Open Sans Semibold", 1, 12),true,Color.WHITE,Color.GRAY));
        Tabela_Ocorrencias.getColumnModel().getColumn(2).setHeaderRenderer(new Pintar_Cabecalho(new java.awt.Font("Open Sans Semibold", 1, 12),true,Color.WHITE,Color.GRAY));
        
        DefaultTableModel modelo =(DefaultTableModel) Tabela_Ocorrencias.getModel();
        Tabela_Ocorrencias.setRowSorter(new TableRowSorter(modelo));
        readJTable();
    }
    public void readJTable(){
        
        DefaultTableModel modelo =(DefaultTableModel) Tabela_Ocorrencias.getModel();
        modelo.setNumRows(0);
        //chamando o DAO
        OcorrenciaDAO dao=new OcorrenciaDAO();
        
        for(Ocorrencia c: dao.read()){
            modelo.addRow(new Object []{
                
                c.getData_ocorrencia(),
                c.getAssunto(),
                c.getResposta()
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Button_VoltaraoMenu_Relatorios = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabela_Ocorrencias = new javax.swing.JTable();
        campo_total = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Button_VoltaraoMenu_Relatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ButtonsUsoGeral/VOLTAR-AO-MENU--3-TRAÇOS.png"))); // NOI18N
        Button_VoltaraoMenu_Relatorios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_VoltaraoMenu_RelatoriosMouseClicked(evt);
            }
        });
        getContentPane().add(Button_VoltaraoMenu_Relatorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, 30));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane2.setForeground(new java.awt.Color(102, 102, 102));
        jScrollPane2.setToolTipText("");
        jScrollPane2.setFocusable(false);
        jScrollPane2.setFont(new java.awt.Font("Open Sans Semibold", 0, 16)); // NOI18N
        jScrollPane2.setMinimumSize(new java.awt.Dimension(10, 10));

        Tabela_Ocorrencias.setBackground(new java.awt.Color(255, 255, 255));
        Tabela_Ocorrencias.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Tabela_Ocorrencias.setFont(new java.awt.Font("Open Sans Semibold", 1, 12)); // NOI18N
        Tabela_Ocorrencias.setForeground(new java.awt.Color(51, 51, 51));
        Tabela_Ocorrencias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "DATA", "ASSUNTO", "RESPOSTA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabela_Ocorrencias.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Tabela_Ocorrencias.setDragEnabled(true);
        Tabela_Ocorrencias.setEditingColumn(0);
        Tabela_Ocorrencias.setEditingRow(0);
        Tabela_Ocorrencias.setGridColor(new java.awt.Color(255, 255, 255));
        Tabela_Ocorrencias.setIntercellSpacing(new java.awt.Dimension(5, 0));
        Tabela_Ocorrencias.setMinimumSize(new java.awt.Dimension(75, 315));
        Tabela_Ocorrencias.setRequestFocusEnabled(false);
        Tabela_Ocorrencias.setRowHeight(35);
        Tabela_Ocorrencias.setSelectionBackground(new java.awt.Color(255, 255, 255));
        Tabela_Ocorrencias.setSelectionForeground(new java.awt.Color(10, 174, 239));
        Tabela_Ocorrencias.setShowHorizontalLines(false);
        Tabela_Ocorrencias.setShowVerticalLines(false);
        Tabela_Ocorrencias.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Tabela_OcorrenciasFocusGained(evt);
            }
        });
        Tabela_Ocorrencias.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Tabela_OcorrenciasKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(Tabela_Ocorrencias);
        if (Tabela_Ocorrencias.getColumnModel().getColumnCount() > 0) {
            Tabela_Ocorrencias.getColumnModel().getColumn(0).setPreferredWidth(30);
            Tabela_Ocorrencias.getColumnModel().getColumn(1).setPreferredWidth(40);
            Tabela_Ocorrencias.getColumnModel().getColumn(2).setPreferredWidth(150);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 500, 100));

        campo_total.setBackground(new java.awt.Color(255, 255, 255));
        campo_total.setFont(new java.awt.Font("Open Sans Semibold", 0, 36)); // NOI18N
        campo_total.setForeground(new java.awt.Color(0, 174, 239));
        campo_total.setBorder(null);
        campo_total.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campo_totalFocusGained(evt);
            }
        });
        getContentPane().add(campo_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, 130, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/BackgroudsUser1/Tela-04--RELATORIOS.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Button_VoltaraoMenu_RelatoriosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_VoltaraoMenu_RelatoriosMouseClicked
        // TODO add your handling code here:
        new Tela3_MenuPrincipalUser1 ().setVisible(true);
            dispose();
    }//GEN-LAST:event_Button_VoltaraoMenu_RelatoriosMouseClicked

    private void Tabela_OcorrenciasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Tabela_OcorrenciasKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_Tabela_OcorrenciasKeyTyped

    private void Tabela_OcorrenciasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Tabela_OcorrenciasFocusGained
        // TODO add your handling code here:
        readJTable();
    }//GEN-LAST:event_Tabela_OcorrenciasFocusGained

    private void campo_totalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campo_totalFocusGained
        // TODO add your handling code here:
        //CONEXOES COM O BANCO E VAR
        Connection con = connectionFactory.getConnection();
        PreparedStatement stmt = null;
        ResultSet rs = null;
        
        //COMANDOS
        try{
            //COMANDO QUE PREPARA
            stmt = con.prepareStatement("select SUM(id_funcionario) from ocorrencia where id_funcionario=1;");
            rs=stmt.executeQuery();

            if(rs.next()){
                campo_total.setText(rs.getString("SUM(id_funcionario)"));
                
            }
           
        }catch(SQLException ex){
            Logger.getLogger(Tela5_RelatoriosUser1.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //FINALIZA/SALVA O BANCO
        finally{
            connectionFactory.closeConnection(con, stmt, rs);
        }
    }//GEN-LAST:event_campo_totalFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela5_RelatoriosUser1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela5_RelatoriosUser1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela5_RelatoriosUser1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela5_RelatoriosUser1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela5_RelatoriosUser1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Button_VoltaraoMenu_Relatorios;
    private javax.swing.JTable Tabela_Ocorrencias;
    private javax.swing.JTextField campo_total;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
