/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sistema;


public class Tela_37_User2_ViewCompras extends javax.swing.JFrame {

    /**
     * Creates new form Tela_37_User2_ViewCompras
     */
    public Tela_37_User2_ViewCompras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Button_Tela37_Anterior = new javax.swing.JLabel();
        Button_37_VoltarConsultas = new javax.swing.JLabel();
        Button_Tela37_RetornarMenu = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Button_Tela37_Anterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ButtonsUser2/anterio.png"))); // NOI18N
        Button_Tela37_Anterior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_Tela37_AnteriorMouseClicked(evt);
            }
        });
        getContentPane().add(Button_Tela37_Anterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 366, 160, 40));

        Button_37_VoltarConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ButtonsUser2/consulta.png"))); // NOI18N
        Button_37_VoltarConsultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_37_VoltarConsultasMouseClicked(evt);
            }
        });
        getContentPane().add(Button_37_VoltarConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 366, -1, 40));

        Button_Tela37_RetornarMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ButtonsUser2/vmen.png"))); // NOI18N
        Button_Tela37_RetornarMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_Tela37_RetornarMenuMouseClicked(evt);
            }
        });
        getContentPane().add(Button_Tela37_RetornarMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 366, 160, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/BackgroundsUser2/24.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Button_Tela37_RetornarMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_Tela37_RetornarMenuMouseClicked
        // TODO add your handling code here:
        new Tela_14_User2_Menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_Button_Tela37_RetornarMenuMouseClicked

    private void Button_37_VoltarConsultasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_37_VoltarConsultasMouseClicked
        // TODO add your handling code here:
        new Tela_29_User2_Consulta().setVisible(true);
        dispose();
    }//GEN-LAST:event_Button_37_VoltarConsultasMouseClicked

    private void Button_Tela37_AnteriorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_Tela37_AnteriorMouseClicked
        // TODO add your handling code here:
        new Tela_36_User2_ComprasClienteLoja().setVisible(true);
        dispose();
    }//GEN-LAST:event_Button_Tela37_AnteriorMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windowns".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_37_User2_ViewCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_37_User2_ViewCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_37_User2_ViewCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_37_User2_ViewCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_37_User2_ViewCompras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Button_37_VoltarConsultas;
    private javax.swing.JLabel Button_Tela37_Anterior;
    private javax.swing.JLabel Button_Tela37_RetornarMenu;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
