/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sistema;

import Model_Bean.Ocorrencia;
import Model_Bean.Ranking;
import Model_DAO.OcorrenciaDAO;
import Model_DAO.RankingDAO;
import java.awt.Color;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import teste.Pintar_Cabecalho;

/**
 *
 * @author Refrigeração Josemaq
 */
public class Tela_32_User2_Ranking extends javax.swing.JFrame {

    /**
     * Creates new form Tela_32_User2_Ranking
     */
    public Tela_32_User2_Ranking() {
        initComponents();
        Tabela_Ranking.getColumnModel().getColumn(0).setHeaderRenderer(new Pintar_Cabecalho(new java.awt.Font("Open Sans Semibold", 1, 12),true,Color.WHITE,Color.GRAY));
        Tabela_Ranking.getColumnModel().getColumn(1).setHeaderRenderer(new Pintar_Cabecalho(new java.awt.Font("Open Sans Semibold", 1, 12),true,Color.WHITE,Color.GRAY));
        Tabela_Ranking.getColumnModel().getColumn(2).setHeaderRenderer(new Pintar_Cabecalho(new java.awt.Font("Open Sans Semibold", 1, 12),true,Color.WHITE,Color.GRAY));
        
        DefaultTableModel modelo =(DefaultTableModel) Tabela_Ranking.getModel();
        Tabela_Ranking.setRowSorter(new TableRowSorter(modelo));
        readJTable();
    }
    public void readJTable(){
        
        DefaultTableModel modelo =(DefaultTableModel) Tabela_Ranking.getModel();
        modelo.setNumRows(0);
        
        //chamando o DAO
        RankingDAO dao=new RankingDAO();
        
        for(Ranking c: dao.read()){
            modelo.addRow(new Object []{
                
                c.getId_ranking(),
                c.getQtd_vendas(),
                c.getCod_barras(),
            });
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Button_Tela32_VoltarMenu = new javax.swing.JLabel();
        Button_Tela32_VoltaRanking = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        Tabela_Ranking = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Button_Tela32_VoltarMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ButtonsUsoGeral/Global.png"))); // NOI18N
        Button_Tela32_VoltarMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_Tela32_VoltarMenuMouseClicked(evt);
            }
        });
        getContentPane().add(Button_Tela32_VoltarMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, 30));

        Button_Tela32_VoltaRanking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ButtonsUser2/voltar.png"))); // NOI18N
        Button_Tela32_VoltaRanking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_Tela32_VoltaRankingMouseClicked(evt);
            }
        });
        getContentPane().add(Button_Tela32_VoltaRanking, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 330, -1, 50));

        jScrollPane5.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane5.setForeground(new java.awt.Color(102, 102, 102));
        jScrollPane5.setToolTipText("");
        jScrollPane5.setFocusable(false);
        jScrollPane5.setFont(new java.awt.Font("Open Sans Semibold", 0, 16)); // NOI18N
        jScrollPane5.setMinimumSize(new java.awt.Dimension(10, 10));

        Tabela_Ranking.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Tabela_Ranking.setFont(new java.awt.Font("Open Sans Semibold", 1, 12)); // NOI18N
        Tabela_Ranking.setForeground(new java.awt.Color(51, 51, 51));
        Tabela_Ranking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID_RANKING", "QTDE_VENDAS", "COD_BARRAS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabela_Ranking.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Tabela_Ranking.setDragEnabled(true);
        Tabela_Ranking.setEditingColumn(0);
        Tabela_Ranking.setEditingRow(0);
        Tabela_Ranking.setGridColor(new java.awt.Color(255, 255, 255));
        Tabela_Ranking.setIntercellSpacing(new java.awt.Dimension(5, 0));
        Tabela_Ranking.setMinimumSize(new java.awt.Dimension(75, 315));
        Tabela_Ranking.setRequestFocusEnabled(false);
        Tabela_Ranking.setRowHeight(35);
        Tabela_Ranking.setSelectionBackground(new java.awt.Color(255, 255, 255));
        Tabela_Ranking.setSelectionForeground(new java.awt.Color(10, 174, 239));
        Tabela_Ranking.setShowHorizontalLines(false);
        Tabela_Ranking.setShowVerticalLines(false);
        Tabela_Ranking.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Tabela_RankingFocusGained(evt);
            }
        });
        Tabela_Ranking.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Tabela_RankingKeyTyped(evt);
            }
        });
        jScrollPane5.setViewportView(Tabela_Ranking);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, -1, 250));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/BackgroundsUser2/19.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -30, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Button_Tela32_VoltaRankingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_Tela32_VoltaRankingMouseClicked
        new Tela_30_User2_ConsultarProdutosCadastrados().setVisible(true);
        dispose();
    }//GEN-LAST:event_Button_Tela32_VoltaRankingMouseClicked

    private void Button_Tela32_VoltarMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_Tela32_VoltarMenuMouseClicked
        // TODO add your handling code here:
        new Tela_14_User2_Menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_Button_Tela32_VoltarMenuMouseClicked

    private void Tabela_RankingFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Tabela_RankingFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_Tabela_RankingFocusGained

    private void Tabela_RankingKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Tabela_RankingKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_Tabela_RankingKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windowns".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_32_User2_Ranking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_32_User2_Ranking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_32_User2_Ranking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_32_User2_Ranking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_32_User2_Ranking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Button_Tela32_VoltaRanking;
    private javax.swing.JLabel Button_Tela32_VoltarMenu;
    private javax.swing.JTable Tabela_Ranking;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane5;
    // End of variables declaration//GEN-END:variables
}
