/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sistema;

import Model_Bean.Pagamento;
import Model_DAO.PagamentoDAO;

/**
 *
 * @author Refrigeração Josemaq
 */
public class Tela6_Forma_de_Pagamento extends javax.swing.JFrame {

    /**
     * Creates new form Tela_6_Forma_de_Pagamento
     */
    public Tela6_Forma_de_Pagamento() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Button_Tela6_Dinheiro = new javax.swing.JLabel();
        Button_Tela6_CardLoja = new javax.swing.JLabel();
        Button_Tela6_Misto = new javax.swing.JLabel();
        Button_VoltaMenu = new javax.swing.JLabel();
        Button_Tela6_Credito = new javax.swing.JLabel();
        Button_Tela6_Debito = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Button_Tela6_Dinheiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ButtonsUser1/Tela-6--Forma-de-Pagamento-Dinheiro.png"))); // NOI18N
        Button_Tela6_Dinheiro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_Tela6_DinheiroMouseClicked(evt);
            }
        });
        getContentPane().add(Button_Tela6_Dinheiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 190, 130));

        Button_Tela6_CardLoja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ButtonsUser1/Tela-6--Forma-de-Pagamento-cartao-loja.png"))); // NOI18N
        Button_Tela6_CardLoja.setText("jLabel6");
        Button_Tela6_CardLoja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_Tela6_CardLojaMouseClicked(evt);
            }
        });
        getContentPane().add(Button_Tela6_CardLoja, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 240, 180, 130));

        Button_Tela6_Misto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ButtonsUser1/Tela-6--Forma-de-Pagamento-Misto.png"))); // NOI18N
        Button_Tela6_Misto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_Tela6_MistoMouseClicked(evt);
            }
        });
        getContentPane().add(Button_Tela6_Misto, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 241, 190, 130));

        Button_VoltaMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ButtonsUsoGeral/Menu-Humburger.png"))); // NOI18N
        Button_VoltaMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_VoltaMenuMouseClicked(evt);
            }
        });
        getContentPane().add(Button_VoltaMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, 40, 50));

        Button_Tela6_Credito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ButtonsUser1/Tela-6--Forma-de-Pagamento-Crédito.png"))); // NOI18N
        Button_Tela6_Credito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_Tela6_CreditoMouseClicked(evt);
            }
        });
        getContentPane().add(Button_Tela6_Credito, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 241, 190, 130));

        Button_Tela6_Debito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ButtonsUser1/Tela-6--Forma-de-Pagamento-Debito.png"))); // NOI18N
        Button_Tela6_Debito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_Tela6_DebitoMouseClicked(evt);
            }
        });
        getContentPane().add(Button_Tela6_Debito, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 240, 200, 130));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/BackgroudsUser1/Tela6--Forma-de-pagamento.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Button_VoltaMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_VoltaMenuMouseClicked
        //Botão retorna Menu principal
        new Tela3_MenuPrincipalUser1 ().setVisible(true);
            dispose();
    }//GEN-LAST:event_Button_VoltaMenuMouseClicked

    private void Button_Tela6_DinheiroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_Tela6_DinheiroMouseClicked
        // INSERE FORMA DE PAGAMENTO NO BD
        //CHAMADA
        Pagamento c=new Pagamento();
        PagamentoDAO dao=new PagamentoDAO();
        
        //passando parametros
        c.setForma_pagamento("Dinheiro");
        
        //EXECUTA
        dao.create(c);

        //Botão Pagamento Dinheiro chama tela do caixa
        new Tela7_Caixa_PDV().setVisible(true);
        dispose();
    }//GEN-LAST:event_Button_Tela6_DinheiroMouseClicked

    private void Button_Tela6_CreditoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_Tela6_CreditoMouseClicked
        // INSERE FORMA DE PAGAMENTO NO BD
        //CHAMADA
        Pagamento c=new Pagamento();
        PagamentoDAO dao=new PagamentoDAO();
        
        //passando parametros
        c.setForma_pagamento("Crédito");
        
        //EXECUTA
        dao.create(c);
        
        //Botão Pagamento Cartão Crédito chama tela do caixa
        new Tela7_Caixa_PDV().setVisible(true);
        dispose();
    }//GEN-LAST:event_Button_Tela6_CreditoMouseClicked

    private void Button_Tela6_MistoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_Tela6_MistoMouseClicked
        // INSERE FORMA DE PAGAMENTO NO BD
        //CHAMADA
        Pagamento c=new Pagamento();
        PagamentoDAO dao=new PagamentoDAO();
        
        //passando parametros
        c.setForma_pagamento("Dinheiro e Card");
        
        //EXECUTA
        dao.create(c);

        //Botão Pagamento Misto chama tela do caixa
        new Tela7_Caixa_PDV().setVisible(true);
        dispose();
    }//GEN-LAST:event_Button_Tela6_MistoMouseClicked

    private void Button_Tela6_DebitoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_Tela6_DebitoMouseClicked
        // INSERE FORMA DE PAGAMENTO NO BD
        //CHAMADA
        Pagamento c=new Pagamento();
        PagamentoDAO dao=new PagamentoDAO();
        
        //passando parametros
        c.setForma_pagamento("Débito");
        
        //EXECUTA
        dao.create(c);

        //Botão Pagamento Debito chama tela do caixa
        new Tela7_Caixa_PDV().setVisible(true);
        dispose();
    }//GEN-LAST:event_Button_Tela6_DebitoMouseClicked

    private void Button_Tela6_CardLojaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_Tela6_CardLojaMouseClicked
        //Botão Pagamento Debito chama tela do caixa
        new Tela8_Solicita_CodCliente_PDV().setVisible(true);
        dispose();
    }//GEN-LAST:event_Button_Tela6_CardLojaMouseClicked

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windowns".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela6_Forma_de_Pagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela6_Forma_de_Pagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela6_Forma_de_Pagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela6_Forma_de_Pagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela6_Forma_de_Pagamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Button_Tela6_CardLoja;
    private javax.swing.JLabel Button_Tela6_Credito;
    private javax.swing.JLabel Button_Tela6_Debito;
    private javax.swing.JLabel Button_Tela6_Dinheiro;
    private javax.swing.JLabel Button_Tela6_Misto;
    private javax.swing.JLabel Button_VoltaMenu;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
