/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sistema;

import Conexao.connectionFactory;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Refrigeração Josemaq
 */
public class Tela_34_User2_MenuCliente extends javax.swing.JFrame {
    public Connection con= connectionFactory.getConnection();
    public Tela_33_User2_ConsultarClientesCadastrados classe = new Tela_33_User2_ConsultarClientesCadastrados();
    public int codigo = classe.cod_cliente;

    /**
     * Creates new form Tela_34_User2_MenuCliente
     */
    public Tela_34_User2_MenuCliente() {
        initComponents();
        Connection con = Conexao_e_Tabela.connectionFactory.getConnection();
        PreparedStatement stmt = null;
        ResultSet rs = null;
        
        //COMANDOS
        try{
            //COMANDO QUE PREPARA
            stmt = con.prepareStatement("select limite,limite,saldo_devedor from cartao where id_cliente ="+ codigo);
            rs=stmt.executeQuery();

            if(rs.next()){
                Text_LimiteAtual.setText(rs.getString("limite"));
                Text_LimiteDisponivel.setText(rs.getString("limite"));
                Text_SaldoDevedor.setText(rs.getString("saldo_devedor"));
                
            }
           
        }catch(SQLException ex){
            Logger.getLogger(Tela_31_User2_SectionProduto.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //FINALIZA/SALVA O BANCO
        finally{
            Conexao_e_Tabela.connectionFactory.closeConnection(con, stmt, rs);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Button_34_AlteraLimite = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Button_Tela34_Compras = new javax.swing.JLabel();
        Button_Tela34_Pagamentos = new javax.swing.JLabel();
        Button_Tela34_RetornarMenu = new javax.swing.JLabel();
        Text_LimiteAtual = new javax.swing.JTextField();
        Text_SaldoDevedor = new javax.swing.JTextField();
        Text_LimiteDisponivel = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Button_34_AlteraLimite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ButtonsUser2/alterar-limite.png"))); // NOI18N
        Button_34_AlteraLimite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_34_AlteraLimiteMouseClicked(evt);
            }
        });
        getContentPane().add(Button_34_AlteraLimite, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 340, 100, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ButtonsUser2/bloquear.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 340, -1, 30));

        Button_Tela34_Compras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ButtonsUser2/compras.png"))); // NOI18N
        Button_Tela34_Compras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_Tela34_ComprasMouseClicked(evt);
            }
        });
        getContentPane().add(Button_Tela34_Compras, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, -1, 30));

        Button_Tela34_Pagamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ButtonsUser2/pagamento.png"))); // NOI18N
        Button_Tela34_Pagamentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_Tela34_PagamentosMouseClicked(evt);
            }
        });
        getContentPane().add(Button_Tela34_Pagamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, -1, 30));

        Button_Tela34_RetornarMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ButtonsUsoGeral/Global.png"))); // NOI18N
        Button_Tela34_RetornarMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_Tela34_RetornarMenuMouseClicked(evt);
            }
        });
        getContentPane().add(Button_Tela34_RetornarMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        Text_LimiteAtual.setBackground(new java.awt.Color(6, 41, 102));
        Text_LimiteAtual.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        Text_LimiteAtual.setForeground(new java.awt.Color(0, 174, 239));
        Text_LimiteAtual.setBorder(null);
        getContentPane().add(Text_LimiteAtual, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 170, 100, 20));

        Text_SaldoDevedor.setBackground(new java.awt.Color(6, 41, 102));
        Text_SaldoDevedor.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        Text_SaldoDevedor.setForeground(new java.awt.Color(0, 174, 239));
        Text_SaldoDevedor.setBorder(null);
        getContentPane().add(Text_SaldoDevedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 290, 100, 20));

        Text_LimiteDisponivel.setBackground(new java.awt.Color(6, 41, 102));
        Text_LimiteDisponivel.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        Text_LimiteDisponivel.setForeground(new java.awt.Color(0, 174, 239));
        Text_LimiteDisponivel.setBorder(null);
        getContentPane().add(Text_LimiteDisponivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 230, 100, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/BackgroundsUser2/21.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Button_Tela34_PagamentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_Tela34_PagamentosMouseClicked
        // TODO add your handling code here:
        new Tela_35_User2_Pagamentos().setVisible(true);
        dispose();
        
    }//GEN-LAST:event_Button_Tela34_PagamentosMouseClicked

    private void Button_Tela34_RetornarMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_Tela34_RetornarMenuMouseClicked
        // TODO add your handling code here:
        new Tela_14_User2_Menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_Button_Tela34_RetornarMenuMouseClicked

    private void Button_Tela34_ComprasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_Tela34_ComprasMouseClicked
        // TODO add your handling code here:
        new Tela_36_User2_ComprasClienteLoja().setVisible(true);
        dispose();
    }//GEN-LAST:event_Button_Tela34_ComprasMouseClicked

    private void Button_34_AlteraLimiteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_34_AlteraLimiteMouseClicked
        // TODO add your handling code here:
        new Tela_38_User2_AlterarLimite().setVisible(true);
        dispose();
    }//GEN-LAST:event_Button_34_AlteraLimiteMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        try{
            String query = "UPDATE cartao SET limite =0.00 WHERE id_cliente ="+codigo;
            PreparedStatement pst= con.prepareStatement(query);
            pst.executeUpdate();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        new Tela_40_User2_BloquearCartao().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windowns".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_34_User2_MenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_34_User2_MenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_34_User2_MenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_34_User2_MenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_34_User2_MenuCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Button_34_AlteraLimite;
    private javax.swing.JLabel Button_Tela34_Compras;
    private javax.swing.JLabel Button_Tela34_Pagamentos;
    private javax.swing.JLabel Button_Tela34_RetornarMenu;
    private javax.swing.JTextField Text_LimiteAtual;
    private javax.swing.JTextField Text_LimiteDisponivel;
    private javax.swing.JTextField Text_SaldoDevedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
